name: Build Flutter Desktop

on:
  push:
    paths-ignore:
      - '**.md'

env:
  FLUTTER_VERSION: '3.32.4'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set GitHub Environment Variables
        run: |
          echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Configure Flutter
        run: flutter config --enable-linux-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: flutter build linux --release --dart-define=version=$GITHUB_SHA_SHORT

      - name: Prepare for upload
        run: |
          mkdir upload
          mv ./build/linux/x64/release/bundle/ ./upload/BlueMapGUI_${{ env.GITHUB_SHA_SHORT }}_Linux_x64/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "BlueMapGUI_${{ env.GITHUB_SHA_SHORT }}_Linux_x64"
          path: './upload/'

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set GitHub Environment Variables
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Configure Flutter
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: flutter build windows --release --dart-define=version=$env:GITHUB_SHA_SHORT

      - name: Prepare for upload
        run: |
          New-Item -Path . -Name "upload" -ItemType "directory"
          Move-Item -Path "./build/windows/x64/runner/Release/" -Destination "./upload/BlueMapGUI_${{ env.GITHUB_SHA_SHORT }}_Windows_x64/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "BlueMapGUI_${{ env.GITHUB_SHA_SHORT }}_Windows_x64"
          path: './upload/'
